version: "3.4"
services:
  geth.dnp.dappnode.eth:
    image: "geth.dnp.dappnode.eth:0.1.17"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.25
    volumes:
      - "geth:/root/.ethereum"
    environment:
      - "EXTRA_OPTION=--http.api eth,engine,net,web3,txpool"
      - P2P_PORTS=30403
      - SYNCMODE=snap
    ports:
      - "30403:30403/tcp"
      - "30403:30403/udp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  geth: {}
